import{createGame,update,clampPlayer,dronePositions,difficulty}from'./engine.mjs?v=3';
import{GameAudio}from'./audio.mjs?v=3';
const audio=new GameAudio();
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),field=$('field');
const ships={guoguo:{name:'果果飞艇',emoji:'🚀',color:'#efa3d2'},diandian:{name:'点点飞艇',emoji:'🛸',color:'#81d9fa'}};
let chosen='guoguo',g=null,W=800,H=560,last=0,visualAge=0,stars=[],particles=[],keys=new Set(),dragging=false,noticeUntil=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){const r=field.getBoundingClientRect(),oldW=W,oldH=H;W=r.width;H=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.round(W*H/4200)},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.2+.3,a:Math.random()*.65+.2}));if(g){g.x*=W/oldW;g.y*=H/oldH;g.w=W;g.h=H;for(const item of g.items){item.x*=W/oldW;item.y*=H/oldH}if(g.boss){g.boss.targetX*=W/oldW;g.boss.targetY*=H/oldH}clampPlayer(g)}}
new ResizeObserver(resize).observe(field);
function hud(){const every=chosen==='guoguo'?10:5,score=g?.score||0;$('skill-label').textContent=chosen==='guoguo'?`僚机护航 · ${g?.drones.length||0} 架`:'激光扫射';$('skill-progress').textContent=`${score%every} / ${every}`;$('skill-fill').style.width=(score%every/every*100)+'%';$('difficulty').textContent=g?.boss?'⚠ BOSS 来了':`难度 ${g?difficulty(g).level:1} / 4`;$('score').textContent=g?.score||0;$('time').textContent=g?Math.ceil(g.time):60;const lives=g?g.lives:3;$('lives').textContent='♥ '.repeat(lives)+'♡ '.repeat(3-lives);$('lives').setAttribute('aria-label',`${lives}颗爱心`);$('time').classList.toggle('urgent',!!g&&g.time<=10);$('pilot-label').textContent=ships[chosen].emoji+' '+ships[chosen].name+' · '+(!g?'等待起飞':g.status==='playing'?'冒险进行中':g.status==='paused'?'休息中':'本次冒险结束')}
function screen(id){for(const v of['start-screen','pause-screen','end-screen'])$(v).hidden=v!==id}
function start(){g=createGame(W,H,chosen);audio.start();particles=[];keys.clear();dragging=false;screen(null);$('pause').disabled=false;$('floating-message').textContent='';hud();canvas.focus({preventScroll:true});last=performance.now()}
function choose(){audio.stop();g=null;particles=[];keys.clear();dragging=false;$('pause').disabled=true;screen('start-screen');$('floating-message').textContent='';hud()}
function pause(){if(!g||g.status!=='playing')return;g.status='paused';audio.stop();keys.clear();dragging=false;screen('pause-screen');$('pause').disabled=true;hud()}
function resume(){if(!g||g.status!=='paused')return;g.status='playing';audio.start();screen(null);$('pause').disabled=false;last=performance.now();hud();canvas.focus({preventScroll:true})}
function finish(){audio.stop();keys.clear();dragging=false;$('pause').disabled=true;const lost=g.status==='lost';$('result-icon').textContent=lost?'📓':'🏆';$('result-badge').textContent=lost?'作业本拦住了去路':'60 秒挑战完成';$('result-title').textContent=lost?'你该写作业啦':'金币满载，返航成功！';$('result-description').textContent=ships[chosen].name+(lost?'已经很努力啦，休息一下再出发。':'躲过了班主任，安全返航！');$('final-score').textContent=g.score;screen('end-screen');hud();$('again').focus({preventScroll:true})}
for(const b of document.querySelectorAll('[data-ship]'))b.onclick=()=>{chosen=b.dataset.ship;for(const v of document.querySelectorAll('[data-ship]')){const active=v===b;v.classList.toggle('selected',active);v.setAttribute('aria-pressed',active)}hud()};
$('sound').onclick=()=>{const on=audio.toggle();$('sound').textContent=on?'♫':'♪̸';$('sound').setAttribute('aria-label',on?'关闭音乐和音效':'开启音乐和音效');$('sound').setAttribute('aria-pressed',String(on));};
$('start').onclick=start;$('again').onclick=start;$('choose').onclick=choose;$('restart-paused').onclick=choose;$('pause').onclick=pause;$('resume').onclick=resume;
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key===' '&&!['INPUT','TEXTAREA','BUTTON','SELECT'].includes(document.activeElement.tagName)&&g){e.preventDefault();if(g.status==='playing')pause();else if(g.status==='paused')resume();return}if(['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s'].includes(key)&&g?.status==='playing'){e.preventDefault();keys.add(key)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function pointer(e){if(g?.status!=='playing')return;const r=canvas.getBoundingClientRect();g.x=e.clientX-r.left;g.y=e.clientY-r.top-(e.pointerType==='touch'?44:0);clampPlayer(g)}
canvas.addEventListener('pointerdown',e=>{if(g?.status!=='playing')return;dragging=true;canvas.setPointerCapture(e.pointerId);pointer(e);e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(dragging)pointer(e)});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
function burst(x,y,color,count){if(reduced)return;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*110;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.5,max:.5,color})}}
function drawEmoji(text,x,y,size,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${size}px "Apple Color Emoji","Noto Color Emoji","Segoe UI Emoji",sans-serif`;ctx.fillText(text,0,0);ctx.restore()}
function background(dt){ctx.clearRect(0,0,W,H);const grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,'#161530');grad.addColorStop(.6,'#101930');grad.addColorStop(1,'#20204b');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#b9a1f208';ctx.lineWidth=1;for(let x=0;x<W;x+=65){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=65){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const s of stars){if(g?.status==='playing'&&!reduced){s.y+=dt*(8+s.r*8);if(s.y>H)s.y=0}ctx.globalAlpha=s.a;ctx.fillStyle='#d6d7ff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.strokeStyle='#a893d614';ctx.beginPath();ctx.ellipse(W*.85,H*.3,W*.27,H*.14,-.5,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.ellipse(W*.13,H*.8,W*.3,H*.15,-.5,0,Math.PI*2);ctx.stroke()}
function drawBoss(){if(!g?.boss)return;const b=g.boss;
if(b.phase==='throwWarn'||b.phase==='clawWarn'){ctx.save();ctx.strokeStyle='#ff8c98';ctx.fillStyle='#ff788b18';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(b.targetX,b.targetY,b.phase==='clawWarn'?42:32,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(b.x,b.y+25);ctx.lineTo(b.targetX,b.targetY);ctx.strokeStyle='#ff8c9850';ctx.stroke();ctx.textAlign='center';ctx.font='bold 12px sans-serif';ctx.fillStyle='#ffd1d8';ctx.fillText(b.phase==='clawWarn'?'钳子锁定！快躲开':'作业来啦！快躲开',Math.max(75,Math.min(W-75,b.targetX)),Math.max(135,b.targetY-52));ctx.restore()}
if(b.phase==='claw'){const x=b.x+(b.targetX-b.x)*b.progress,y=b.y+(b.targetY-b.y)*b.progress;ctx.save();ctx.lineWidth=8;ctx.strokeStyle='#5c638a';ctx.beginPath();ctx.moveTo(b.x,b.y+15);ctx.lineTo(x,y);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='#c4c7e5';ctx.stroke();ctx.restore();drawEmoji('🗜️',x,y,50);}
ctx.save();ctx.fillStyle='#fd779419';ctx.strokeStyle='#ff9cab80';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(b.x,b.y+9,44,35,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();drawEmoji('👩‍🏫',b.x,b.y+5,52);drawEmoji('💢',b.x+31,b.y-17,22);
ctx.save();ctx.textAlign='center';ctx.font='bold 13px sans-serif';ctx.fillStyle='#ffd0dc';ctx.fillText('生气的班主任',b.x,b.y-35);ctx.font='10px sans-serif';ctx.fillStyle='#dfacbc';ctx.fillText('无敌 BOSS · 坚持到时间结束',b.x,b.y+53);ctx.restore();}
function draw(dt){background(dt);if(!g){drawEmoji('🪙',W*.11,H*.24,30,-.3);drawEmoji('📓',W*.86,H*.78,42,.3);drawEmoji('🪙',W*.85,H*.2,25,.2);return}for(const item of g.items){if(item.kind==='coin'){ctx.shadowColor='#e2b63d';ctx.shadowBlur=9;drawEmoji('🪙',item.x,item.y,30,Math.sin(visualAge*2+item.x)*.15);ctx.shadowBlur=0}else drawEmoji('📓',item.x,item.y,44,item.angle)}for(const beam of g.lasers){ctx.save();ctx.globalAlpha=Math.min(1,beam.life*5);const glow=ctx.createLinearGradient(beam.x-beam.width/2,0,beam.x+beam.width/2,0);glow.addColorStop(0,'#50bfff00');glow.addColorStop(.3,'#73dcff88');glow.addColorStop(.5,'#f0ffff');glow.addColorStop(.7,'#73dcff88');glow.addColorStop(1,'#50bfff00');ctx.fillStyle=glow;ctx.fillRect(beam.x-beam.width/2,0,beam.width,beam.y);ctx.restore()}if(g.drones.length){ctx.strokeStyle='#f4a6d530';ctx.setLineDash([3,7]);ctx.beginPath();ctx.arc(g.x,g.y,56,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);for(const d of dronePositions(g)){ctx.shadowColor='#f6a1d5';ctx.shadowBlur=12;drawEmoji('🛸',d.x,d.y,25);ctx.shadowBlur=0}}const s=ships[chosen];const inv=g.invulnerable>0;ctx.save();ctx.globalAlpha=inv&&Math.floor(g.age*12)%2===0?.4:1;ctx.fillStyle=s.color+'18';ctx.strokeStyle=s.color+'70';ctx.lineWidth=2;ctx.beginPath();ctx.arc(g.x,g.y,30,0,Math.PI*2);ctx.fill();ctx.stroke();if(inv){ctx.strokeStyle='#f9dae4';ctx.setLineDash([4,5]);ctx.beginPath();ctx.arc(g.x,g.y,36,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}drawEmoji(s.emoji,g.x,g.y,47);ctx.restore();for(const p of particles){if(g.status==='playing'){p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt}ctx.globalAlpha=Math.max(0,p.t/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;particles=particles.filter(p=>p.t>0);drawBoss()}
function loop(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;visualAge+=dt;if(g?.status==='playing'){const left=keys.has('arrowleft')||keys.has('a'),right=keys.has('arrowright')||keys.has('d'),up=keys.has('arrowup')||keys.has('w'),down=keys.has('arrowdown')||keys.has('s');let dx=Number(right)-Number(left),dy=Number(down)-Number(up),norm=Math.hypot(dx,dy)||1;const speed=Math.max(260,W*.48);g.x+=dx/norm*speed*dt;g.y+=dy/norm*speed*dt;clampPlayer(g);for(const ev of update(g,dt)){audio.fx(ev.type);if(ev.type==='boss'){$('floating-message').textContent='生气的班主任来了！坚持最后 15 秒！';noticeUntil=now+2200}if(ev.type==='burn')burst(ev.x,ev.y,'#8fe6ff',12);if(ev.type==='droneLost')burst(ev.x,ev.y,'#ffb9e0',14);if(ev.type==='drone'||ev.type==='laser'){$('floating-message').textContent=ev.type==='drone'?'僚机加入！一起收金币！':'激光发射！金币作业本一起扫！';noticeUntil=now+1100}if(ev.type==='coin')burst(ev.x,ev.y,'#ffe09a',8);if(ev.type==='hit'){burst(ev.x,ev.y,'#ffa5c2',13);$('hit-flash').classList.remove('flash');void $('hit-flash').offsetWidth;$('hit-flash').classList.add('flash');$('floating-message').textContent='哎呀，碰到作业本了！';noticeUntil=now+1300}if(ev.type==='end')finish()}hud();if(now>noticeUntil)$('floating-message').textContent=''}draw(dt);requestAnimationFrame(loop)}
resize();hud();requestAnimationFrame(loop);
