export class GameAudio{
constructor(){this.ctx=null;this.enabled=true;this.running=false;this.step=0;this.clock=null;this.next=0}
init(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return false;if(!this.ctx){this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=this.enabled?.45:0;this.master.connect(this.ctx.destination)}this.ctx.resume().catch(()=>{});return true}catch{return false}}
note(freq,duration=.15,volume=.08,type='sine',when=0,endFreq=null){if(!this.ctx||!this.enabled)return;const t=when||this.ctx.currentTime,o=this.ctx.createOscillator(),a=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+duration);a.gain.setValueAtTime(0,t);a.gain.linearRampToValueAtTime(volume,t+.012);a.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(a);a.connect(this.master);o.start(t);o.stop(t+duration+.03);o.onended=()=>{o.disconnect();a.disconnect()}}
start(){if(!this.init())return;this.running=true;this.master.gain.setTargetAtTime(this.enabled?.45:0,this.ctx.currentTime,.025);this.next=this.ctx.currentTime+.04;if(!this.clock)this.clock=setInterval(()=>this.tick(),70)}
stop(){this.running=false;if(this.clock){clearInterval(this.clock);this.clock=null}if(this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.05)}
toggle(){this.enabled=!this.enabled;this.init();if(this.ctx)this.master.gain.setTargetAtTime(this.enabled?.45:0,this.ctx.currentTime,.03);return this.enabled}
tick(){if(!this.running||!this.ctx||this.ctx.state!=='running')return;const melody=[72,76,79,83,79,76,74,79,71,74,79,81,79,74,72,76,69,72,76,79,76,72,71,74,67,71,74,79,74,71,72,0],bass=[48,43,45,43],hz=n=>440*2**((n-69)/12);if(this.next<this.ctx.currentTime-.3)this.next=this.ctx.currentTime;while(this.next<this.ctx.currentTime+.13){let n=melody[this.step%melody.length];if(n)this.note(hz(n),.19,.065,'triangle',this.next);if(this.step%4===0)this.note(hz(bass[Math.floor(this.step/8)%4]),.36,.075,'sine',this.next);this.next+=.225;this.step++}}
fx(kind){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime;if(kind==='coin'){this.note(1050,.085,.11,'sine',t);this.note(1500,.11,.07,'sine',t+.05)}else if(kind==='boss'){[220,220,165].forEach((f,i)=>this.note(f,.3,.1,'triangle',t+i*.25))}else if(kind==='warning'){this.note(550,.16,.09,'sine',t);this.note(550,.16,.09,'sine',t+.25)}else if(kind==='claw'){this.note(260,.35,.08,'sawtooth',t,70)}else if(kind==='throw'){this.note(400,.18,.06,'triangle',t,120)}else if(kind==='laser'){this.note(1100,.28,.08,'sawtooth',t,95)}else if(kind==='hit'||kind==='droneLost'){this.note(180,.22,.12,'triangle',t,55)}else if(kind==='drone'){[660,880,1320].forEach((f,i)=>this.note(f,.16,.09,'sine',t+i*.09))}}
}
